# Generated by Django 3.1.5 on 2021-03-11 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='travel_time',
            field=models.PositiveSmallIntegerField(verbose_name='Travel time'),
        ),
    ]
